from crewai.tools import BaseTool
from datetime import datetime

class HTMLTool(BaseTool):
    name: str = "generate_html"
    description: str = "将新闻数据生成为响应式HTML简报页面"

    def _run(self, briefings_str: str = "{}", date: str = "") -> str:
        import json
        try:
            briefings = json.loads(briefings_str.replace("'", '"'))
        except:
            briefings = {}

        if not date:
            date = datetime.now().strftime("%Y-%m-%d")

        html = self._generate_html(briefings, date)
        return html

    def _generate_html(self, briefings, date):
        header = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>每日科技简报 - """ + date + """</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { 
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            background: #f5f5f5; 
            line-height: 1.6;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px 20px;
            text-align: center;
        }
        .header h1 { font-size: 2.5em; margin-bottom: 10px; }
        .header .date { opacity: 0.9; font-size: 1.1em; }
        .container { max-width: 1200px; margin: 0 auto; padding: 20px; }
        .category { margin-bottom: 30px; }
        .category-title {
            font-size: 1.5em;
            color: #333;
            margin-bottom: 15px;
            padding-left: 15px;
            border-left: 4px solid #667eea;
        }
        .card {
            background: white;
            border-radius: 12px;
            padding: 20px;
            margin-bottom: 15px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            transition: transform 0.2s;
        }
        .card:hover { transform: translateY(-2px); box-shadow: 0 4px 12px rgba(0,0,0,0.15); }
        .card-title {
            font-size: 1.2em;
            color: #333;
            margin-bottom: 8px;
            font-weight: 600;
        }
        .card-summary { color: #666; margin-bottom: 10px; }
        .card-meta {
            display: flex;
            justify-content: space-between;
            align-items: center;
            font-size: 0.9em;
            color: #999;
        }
        .card-link {
            color: #667eea;
            text-decoration: none;
        }
        .card-link:hover { text-decoration: underline; }
        .badge {
            display: inline-block;
            padding: 4px 12px;
            border-radius: 20px;
            font-size: 0.8em;
            margin-right: 8px;
        }
        .badge-ai { background: #e3f2fd; color: #1976d2; }
        .badge-product { background: #f3e5f5; color: #7b1fa2; }
        .badge-industry { background: #e8f5e9; color: #388e3c; }
        .badge-funding { background: #fff3e0; color: #f57c00; }
        .badge-tech { background: #fce4ec; color: #c2185b; }
        .footer {
            text-align: center;
            padding: 40px;
            color: #999;
            font-size: 0.9em;
        }
        @media (max-width: 768px) {
            .header h1 { font-size: 1.8em; }
            .container { padding: 10px; }
            .card { padding: 15px; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>每日科技简报</h1>
        <div class="date">""" + date + """</div>
        <div style="margin-top: 10px; font-size: 0.9em;">由 AI Agent 自动生成</div>
    </div>
    <div class="container">
        """ + self._generate_categories(briefings) + """
    </div>
    <div class="footer">
        <p>Generated by Daily Tech Briefing AI Agent | """ + datetime.now().strftime("%Y-%m-%d %H:%M") + """</p>
    </div>
</body>
</html>"""
        return header

    def _generate_categories(self, briefings):
        html = ""
        badge_map = {
            "AI": "badge-ai",
            "产品发布": "badge-product",
            "行业动态": "badge-industry",
            "融资并购": "badge-funding",
            "技术趋势": "badge-tech"
        }

        for category, items in briefings.items():
            if not items:
                continue
            badge_class = badge_map.get(category, "badge-tech")
            html += '<div class="category">\n'
            html += '<h2 class="category-title"><span class="badge ' + badge_class + '">' + category + '</span></h2>\n'

            for item in items:
                html += '<div class="card">\n'
                html += '<div class="card-title">' + str(item.get("title", "无标题")) + '</div>\n'
                html += '<div class="card-summary">' + str(item.get("summary", "暂无摘要")) + '</div>\n'
                html += '<div class="card-meta">\n'
                html += '<span>' + str(item.get("source", "未知来源")) + '</span>\n'
                html += '<a href="' + str(item.get("link", "#")) + '" target="_blank" class="card-link">阅读原文 &rarr;</a>\n'
                html += '</div>\n'
                html += '</div>\n'
            html += '</div>\n'

        return html

html_tool = HTMLTool()
